import type { NextPage } from "next";
import { useEffect, useState } from "react";
import { useRecoilState, useRecoilValue, useSetRecoilState } from "recoil";
import Head from "next/head";

import styles from "@styles/Home.module.css";
import MainForm from "@components/Form/MainForm";
import Search from "@components/Search/Search";
import profileState from "@store/index";

import { _axios } from "utilities/_axios";
import { readFromCollection } from "@firebase/firestoreReadWrite";

interface profile {
	id: string;
	interests: string[];
	status: string;
	timeStamp: Object;
}

export const getServerSideProps = async () => {
	const res = await readFromCollection("profiles");
	const data = await res;

	const query = data.find((profile) => profile.id === profileState.id);
	if (query) {
		return {
			props: {
				data: query,
				notFound: false,
			},
		};
	}
	return {
		props: { data: null, notFound: true },
	};
};

const Home: NextPage = ({ data, notFound }) => {
	const [searching, setSearching] = useState(false);
	const profile: profile = useRecoilValue(profileState);

	if (data) {
		console.log(data.data.id);
	} else {
		console.log(notFound);
	}
	console.log("Profile ID " + profile.id);

	return (
		<div className={styles.container}>
			<Head>
				<title>Clique</title>
				<meta name="talk to a stranger" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{!searching && <MainForm setSearchState={setSearching} />}
			{searching && <Search />}
		</div>
	);
};

export default Home;
