import type { NextPage } from 'next'
import { useState } from 'react'

import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Header from '../components/Header'




const Home: NextPage = () => {
  const [inputValue, setInputValue] = useState('')

  const onInputChange = (e:Event):void => {
    setInputValue(e.target.value)
  }

  const handleSubmit = (e:Event):void => {
    console.log('submitted');
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Clique</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <p className={styles.p}>type your interests here</p>
        <form className={styles.form}>
          <input placeholder="cars, Sun Tzu, Vakkachan" className={styles.input} onChange={onInputChange}></input>
          <button type='submit' className={styles.button} onClick={handleSubmit}>GO !!</button>
        </form>
      </main>

    </div>
  )
}

export default Home
