import type { NextPage } from "next";
import { useState } from "react";
import { useRecoilState, useRecoilValue, useSetRecoilState } from "recoil";
import Head from "next/head";

import MainForm from "@components/Form/MainForm";
import styles from "@styles/Home.module.css";
import profileState from "@store/index";
import Search from "@components/Search/Search";

const Home: NextPage = () => {
	const [searching, setSearching] = useState(false);
	return (
		<div className={styles.container}>
			<Head>
				<title>Clique</title>
				<meta name="talk to a stranger" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{!searching && <MainForm setSearchState={setSearching} />}
			{searching && <Search />}
		</div>
	);
};

export default Home;
